In [11]:
import pandas as pd
from sqlalchemy import create_engine
import os

In [2]:
pd.__version__

'2.2.0'

In [12]:
csv_url = 'https://raw.githubusercontent.com/TalaatHasanin/DE_ZoomCamp/main/module1/docker/output.csv'
os.system(f"wget {csv_url} -O test.csv")
test_df = pd.read_csv("test.csv")
test_df

FileNotFoundError: [Errno 2] No such file or directory: 'test.csv'

In [3]:
df = pd.read_csv("yellow_tripdata_2021-01.csv", nrows=100)

In [4]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [5]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:00,2021-01-01 00:36:00,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:00,2021-01-01 00:52:00,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:00,2021-01-01 01:11:00,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:00,2021-01-01 00:31:00,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:00,2021-01-01 00:48:00,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,2021-01-01 00:12:00,2021-01-01 00:26:00,1,4.13,1,N,161,226,1,14.5,0.5,0.5,3.66,0.0,0.3,21.96,2.5
96,2,2021-01-01 00:23:00,2021-01-01 00:35:00,2,4.12,1,N,162,74,2,13.5,0.5,0.5,0.00,0.0,0.3,17.30,2.5
97,2,2021-01-01 00:46:00,2021-01-01 00:54:00,2,2.22,1,N,144,170,1,9.0,0.5,0.5,2.56,0.0,0.3,15.36,2.5
98,2,2021-01-01 00:28:00,2021-01-01 00:51:00,1,7.11,1,N,264,264,2,23.5,0.5,0.5,0.00,0.0,0.3,24.80,0.0
99,2,2021-01-01 00:42:00,2021-01-01 00:54:00,3,1.61,1,N,229,237,2,9.5,0.5,0.5,0.00,0.0,0.3,13.30,2.5

In [6]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [7]:
connection = engine.connect()

In [8]:
schema = pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine)
print(schema)

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [9]:
df_iter = pd.read_csv("yellow_tripdata_2021-01.csv", iterator=True, chunksize=100000)

In [10]:
df = next(df_iter)
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,1/1/2021 0:30,1/1/2021 0:36,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,1/1/2021 0:51,1/1/2021 0:52,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,1/1/2021 0:43,1/1/2021 1:11,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,1/1/2021 0:15,1/1/2021 0:31,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,1/1/2021 0:31,1/1/2021 0:48,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,1/4/2021 14:04,1/4/2021 14:08,3,0.70,1,N,234,224,2,5.0,2.5,0.5,0.00,0.0,0.3,8.30,2.5
99996,1,1/4/2021 14:18,1/4/2021 14:35,2,3.30,1,N,234,236,1,14.5,2.5,0.5,3.55,0.0,0.3,21.35,2.5
99997,1,1/4/2021 14:42,1/4/2021 14:59,2,4.70,1,N,236,79,1,17.0,2.5,0.5,4.05,0.0,0.3,24.35,2.5
99998,2,1/4/2021 14:39,1/4/2021 15:09,2,17.95,2,N,132,148,1,52.0,0.0,0.5,5.00,0.0,0.3,60.30,2.5
99999,2,1/4/2021 14:49,1/4/2021 14:54,5,0.37,1,N,236,236,2,5.0,0.0,0.5,0.00,0.0,0.3,8.30,2.5

In [11]:
len(df)

100000

In [12]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [13]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [14]:
%time df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

CPU times: total: 3.36 s
Wall time: 9.22 s

1000

In [15]:
from time import time

In [17]:
while True:
    df = next(df_iter)
    t_begin = time()
    
    df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
    df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)
    
    df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')
    t_end = time()
    
    print(f'inserted another chunck...., took {t_end - t_begin:.3f}')

inserted another chunck...., took 8.550
inserted another chunck...., took 9.606
inserted another chunck...., took 8.736
inserted another chunck...., took 8.678
inserted another chunck...., took 8.405
inserted another chunck...., took 8.231
inserted another chunck...., took 8.744
inserted another chunck...., took 8.926
inserted another chunck...., took 9.919
inserted another chunck...., took 4.897

StopIteration: